spring.application.name=interview-portal
server.port=8521
spring.datasource.url= jdbc:h2:file:./data/testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.defer-datasource-initialization=true

server.ssl.enabled=true
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=Krishna123
server.ssl.key-store-type=PKCS12
server.ssl.key-alias=local

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.thymeleaf.cache=false
spring.web.resources.cache.period=0
spring.web.resources.chain.cache=false

spring.devtools.restart.enabled=true

# Chat model
spring.ai.openai.chat.options.model=gpt-4o-mini

# Speech-to-text (Whisper)
spring.ai.openai.audio.transcription.model=whisper-1

# Text-to-speech
spring.ai.openai.audio.speech.model=gpt-4o-mini-tts
spring.ai.openai.api-key= ${OPENAI_API_KEY}

spring.config.import=classpath:domain-dictionary.yml,classpath:skill-normalization.yml